CREATE USER suafbsdbuser WITH PASSWORD 'XXXXXXXXXXXX';

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE suafbsdb TO suafbsdbuser;
GRANT ALL PRIVILEGES ON SCHEMA public TO suafbsdbuser;
GRANT ALL PRIVILEGES ON SCHEMA core TO suafbsdbuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO suafbsdbuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA core TO suafbsdbuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO suafbsdbuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA core TO suafbsdbuser;

-- Set default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO suafbsdbuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT ALL PRIVILEGES ON TABLES TO suafbsdbuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO suafbsdbuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT ALL PRIVILEGES ON SEQUENCES TO suafbsdbuser;
